// src/permissions.js
export const PERMISSIONS = {
  // Visibilidad de Pestañas
  VER_TABLA_GENERAL: 'VER_TABLA_GENERAL',
  VER_INFORMES: 'VER_INFORMES',
  VER_VENTAS: 'VER_VENTAS',
  VER_ALMACEN: 'VER_ALMACEN',
  REGISTRAR: 'REGISTRAR',
  
  // Acciones Específicas
  EDITAR_REGISTRO: 'EDITAR_REGISTRO',
  ELIMINAR_REGISTRO: 'ELIMINAR_REGISTRO',
  MARCAR_VENDIDO: 'MARCAR_VENDIDO',
  VER_FINANZAS: 'VER_FINANZAS', // Permite ver costos, utilidad, etc.
  FORMATEAR_INVENTARIO: 'FORMATEAR_INVENTARIO',

  // Administración del Sistema
  GESTIONAR_USUARIOS: 'GESTIONAR_USUARIOS', // Para acceder al nuevo panel
  GESTIONAR_ROLES: 'GESTIONAR_ROLES',       // Para crear y editar roles
  PIN_LOGIN: 'PIN_LOGIN', // Para forzar el login con PIN
};

// Asignación de permisos a los roles existentes.
// Esto simula lo que estaría en una base de datos y que el super_admin podría editar.
export const ROLES_PERMISSIONS = {
  super_admin: Object.values(PERMISSIONS), // El super_admin tiene todos los permisos
  admin_2: [
    PERMISSIONS.VER_TABLA_GENERAL, PERMISSIONS.VER_INFORMES, PERMISSIONS.VER_VENTAS,
    PERMISSIONS.VER_ALMACEN, PERMISSIONS.REGISTRAR, PERMISSIONS.EDITAR_REGISTRO,
    PERMISSIONS.ELIMINAR_REGISTRO, PERMISSIONS.MARCAR_VENDIDO, PERMISSIONS.VER_FINANZAS,
  ],
  administrador_ventas: [
    PERMISSIONS.VER_TABLA_GENERAL, PERMISSIONS.VER_INFORMES, PERMISSIONS.VER_VENTAS,
    PERMISSIONS.VER_ALMACEN, PERMISSIONS.MARCAR_VENDIDO, PERMISSIONS.VER_FINANZAS,
  ],
  vendedor: [
    PERMISSIONS.VER_TABLA_GENERAL, PERMISSIONS.VER_VENTAS, PERMISSIONS.MARCAR_VENDIDO,
    PERMISSIONS.REGISTRAR, PERMISSIONS.EDITAR_REGISTRO,
  ],
};